services:
  mint-redeem:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    command: ["mint-redeem"]
    restart: unless-stopped
    environment:
      CONFIG: /app/config.toml
      CHAIN: ${CHAIN}
      DB_TYPE: postgres
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RPC_URL: ${RPC_URL}
      RPC_API_KEY: ${RPC_API_KEY}
      XRP_RPC_URL: ${XRP_RPC_URL}
      XRP_RPC_API_KEY: ${XRP_RPC_API_KEY}
      LOAD_TEST_XRP_DISTRIBUTOR_SEED: ${LOAD_TEST_XRP_DISTRIBUTOR_SEED}
      LOAD_TEST_NAT_DISTRIBUTOR_PVK: ${LOAD_TEST_NAT_DISTRIBUTOR_PVK}
      LOAD_TEST_AGENT_VAULTS: ${LOAD_TEST_AGENT_VAULTS}
    volumes:
      - ${CONFIG}:/app/config.toml
      - ./fasset-bots-config:/app/fasset-bots-config
      - ./fasset-bots-logs:/app/log
      - ./fasset-bots-qa-logs:/app/logs
    depends_on:
      db-postgres:
        condition: service_healthy

  db-postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  db_data: