services:
  core-vault-management:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    network_mode: host
    command: ["mint-redeem"]
    restart: unless-stopped
    environment:
      CONFIG: /app/config.toml
      CHAIN: ${CHAIN}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RPC_URL: ${RPC_URL}
      RPC_API_KEY: ${RPC_API_KEY}
      XRP_RPC_URL: ${XRP_RPC_URL}
      XRP_RPC_API_KEY: ${XRP_RPC_API_KEY}
      LOAD_TEST_XRP_DISTRIBUTOR_SEED: ${LOAD_TEST_XRP_DISTRIBUTOR_SEED}
      LOAD_TEST_NAT_DISTRIBUTOR_PVK: ${LOAD_TEST_NAT_DISTRIBUTOR_PVK}
      LOAD_TEST_AGENT_VAULTS: ${LOAD_TEST_AGENT_VAULTS}
    volumes:
      - ${CONFIG}:/app/config.toml
      - ./fasset-bots-config:/app/fasset-bots-config
      - ./fasset-bots-logs:/app/log
      - ./fasset-bots-qa-logs:/app/logs
